packages:
  - playground
  - packages/**
catalog:
  '@antfu/eslint-config': ^3.8.0
  '@babel/types': ^7.26.0
  '@types/fs-extra': ^11.0.4
  '@types/node': ^22.9.0
  '@types/postcss-js': ^4.0.4
  '@unocss/core': ^0.64.0
  '@unocss/eslint-plugin': ^0.64.0
  '@unocss/nuxt': ^0.64.0
  '@unocss/preset-attributify': ^0.64.0
  '@unocss/preset-icons': ^0.64.0
  '@unocss/preset-mini': ^0.64.0
  '@unocss/preset-rem-to-px': ^0.64.0
  '@unocss/preset-tagify': ^0.64.0
  '@unocss/preset-typography': ^0.64.0
  '@unocss/preset-uno': ^0.64.0
  '@unocss/preset-web-fonts': ^0.64.0
  '@unocss/transformer-compile-class': ^0.64.0
  '@unocss/transformer-directives': ^0.64.0
  '@unocss/transformer-variant-group': ^0.64.0
  '@vitejs/plugin-vue': ^5.1.4
  bumpp: ^9.8.1
  eslint: ^9.14.0
  esno: ^4.8.0
  fs-extra: ^11.2.0
  lint-staged: ^15.2.10
  magic.css: ^1.4.8
  postcss: ^8.4.47
  postcss-js: ^4.0.1
  simple-git-hooks: ^2.11.1
  taze: ^0.18.0
  typescript: ^5.6.3
  unbuild: ^2.0.0
  unocss: ^0.64.0
  unocss-preset-scrollbar: ^0.3.1
  vite: ^5.4.10
  vitest: ^2.1.4
  vue: ^3.5.12
  vue-tsc: ^2.1.10
