packages:
  - playground
  - packages/**

catalog:
  '@antfu/eslint-config': ^4.14.1
  '@babel/types': ^7.27.6
  '@types/fs-extra': ^11.0.4
  '@types/node': ^24.0.3
  '@types/postcss-js': ^4.0.4
  '@unocss/core': ^66.2.1
  '@unocss/eslint-plugin': ^66.2.1
  '@unocss/preset-attributify': ^66.2.1
  '@unocss/preset-icons': ^66.2.1
  '@unocss/preset-legacy-compat': ^66.2.1
  '@unocss/preset-mini': ^66.2.1
  '@unocss/preset-rem-to-px': ^66.2.1
  '@unocss/preset-tagify': ^66.2.1
  '@unocss/preset-typography': ^66.2.1
  '@unocss/preset-wind3': ^66.2.1
  '@unocss/preset-wind4': ^66.2.1
  '@unocss/preset-web-fonts': ^66.2.1
  '@unocss/transformer-compile-class': ^66.2.1
  '@unocss/transformer-directives': ^66.2.1
  '@unocss/transformer-variant-group': ^66.2.1
  '@vitejs/plugin-vue': ^5.2.4
  bumpp: ^10.1.1
  eslint: ^9.29.0
  esno: ^4.8.0
  fs-extra: ^11.3.0
  lint-staged: ^16.1.2
  postcss: ^8.5.5
  postcss-js: ^4.0.1
  simple-git-hooks: ^2.13.0
  taze: ^19.1.0
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: ^66.2.1
  unocss-preset-magicss: ^1.0.0
  vite: ^6.3.5
  vitepress: ^1.6.3
  vitest: ^3.2.3
  vue: ^3.5.16
  vue-tsc: ^2.2.10
  eslint-import-resolver-node: ^0.3.9
  execa: ^9.6.0
  tsdown: ^0.12.7
