packages:
  - playground
  - packages/**
catalog:
  '@antfu/eslint-config': ^3.14.0
  '@babel/types': ^7.26.5
  '@types/fs-extra': ^11.0.4
  '@types/node': ^22.10.6
  '@types/postcss-js': ^4.0.4
  '@unocss/core': ^65.4.0
  '@unocss/eslint-plugin': ^65.4.0
  '@unocss/nuxt': ^65.4.0
  '@unocss/preset-attributify': ^65.4.0
  '@unocss/preset-icons': ^65.4.0
  '@unocss/preset-legacy-compat': ^65.4.0
  '@unocss/preset-mini': ^65.4.0
  '@unocss/preset-rem-to-px': ^65.4.0
  '@unocss/preset-tagify': ^65.4.0
  '@unocss/preset-typography': ^65.4.0
  '@unocss/preset-uno': ^65.4.0
  '@unocss/preset-web-fonts': ^65.4.0
  '@unocss/transformer-compile-class': ^65.4.0
  '@unocss/transformer-directives': ^65.4.0
  '@unocss/transformer-variant-group': ^65.4.0
  '@vitejs/plugin-vue': ^5.2.1
  bumpp: ^9.10.0
  eslint: ^9.18.0
  esno: ^4.8.0
  fs-extra: ^11.2.0
  lint-staged: ^15.3.0
  postcss: ^8.5.1
  postcss-js: ^4.0.1
  simple-git-hooks: ^2.11.1
  taze: ^18.1.0
  typescript: ^5.7.3
  unbuild: ^3.3.1
  unocss: ^65.4.0
  unocss-preset-magicss: ^1.0.0
  unocss-preset-scrollbar: ^0.3.1
  vite: ^6.0.7
  vitepress: ^1.5.0
  vitest: ^2.1.8
  vue: ^3.5.13
  vue-tsc: ^2.2.0
