packages:
  - playground
  - packages/**
catalog:
  '@antfu/eslint-config': ^4.11.0
  '@babel/types': ^7.27.0
  '@types/fs-extra': ^11.0.4
  '@types/node': ^22.13.13
  '@types/postcss-js': ^4.0.4
  '@unocss/core': ^66.1.0-beta.7
  '@unocss/eslint-plugin': ^66.1.0-beta.7
  '@unocss/nuxt': ^66.1.0-beta.7
  '@unocss/preset-attributify': ^66.1.0-beta.7
  '@unocss/preset-icons': ^66.1.0-beta.7
  '@unocss/preset-legacy-compat': ^66.1.0-beta.7
  '@unocss/preset-mini': ^66.1.0-beta.7
  '@unocss/preset-rem-to-px': ^66.1.0-beta.7
  '@unocss/preset-tagify': ^66.1.0-beta.7
  '@unocss/preset-typography': ^66.1.0-beta.7
  '@unocss/preset-uno': ^66.1.0-beta.7
  '@unocss/preset-web-fonts': ^66.1.0-beta.7
  '@unocss/transformer-compile-class': ^66.1.0-beta.7
  '@unocss/transformer-directives': ^66.1.0-beta.7
  '@unocss/transformer-variant-group': ^66.1.0-beta.7
  '@vitejs/plugin-vue': ^5.2.3
  bumpp: ^10.1.0
  eslint: ^9.23.0
  esno: ^4.8.0
  fs-extra: ^11.3.0
  lint-staged: ^15.5.0
  postcss: ^8.5.3
  postcss-js: ^4.0.1
  simple-git-hooks: ^2.12.1
  taze: ^19.0.2
  typescript: ^5.8.2
  unbuild: ^3.5.0
  unocss: ^66.1.0-beta.7
  unocss-preset-magicss: ^1.0.0
  vite: ^6.2.3
  vitepress: ^1.6.3
  vitest: ^3.0.9
  vue: ^3.5.13
  vue-tsc: ^2.2.8
