packages:
  - playground
  - packages/**
catalog:
  '@antfu/eslint-config': ^3.12.0
  '@babel/types': ^7.26.3
  '@types/fs-extra': ^11.0.4
  '@types/node': ^22.10.2
  '@types/postcss-js': ^4.0.4
  '@unocss/core': ^0.65.2
  '@unocss/eslint-plugin': ^0.65.2
  '@unocss/nuxt': ^0.65.2
  '@unocss/preset-attributify': ^0.65.2
  '@unocss/preset-icons': ^0.65.2
  '@unocss/preset-legacy-compat': ^0.65.2
  '@unocss/preset-mini': ^0.65.2
  '@unocss/preset-rem-to-px': ^0.65.2
  '@unocss/preset-tagify': ^0.65.2
  '@unocss/preset-typography': ^0.65.2
  '@unocss/preset-uno': ^0.65.2
  '@unocss/preset-web-fonts': ^0.65.2
  '@unocss/transformer-compile-class': ^0.65.2
  '@unocss/transformer-directives': ^0.65.2
  '@unocss/transformer-variant-group': ^0.65.2
  '@vitejs/plugin-vue': ^5.2.1
  bumpp: ^9.9.2
  eslint: ^9.17.0
  esno: ^4.8.0
  fs-extra: ^11.2.0
  lint-staged: ^15.2.11
  postcss: ^8.4.49
  postcss-js: ^4.0.1
  simple-git-hooks: ^2.11.1
  taze: ^0.18.0
  typescript: ^5.7.2
  unbuild: ^3.0.1
  unocss: ^0.65.2
  unocss-preset-magicss: ^0.1.3
  unocss-preset-scrollbar: ^0.3.1
  vite: ^6.0.5
  vitest: ^2.1.8
  vue: ^3.5.13
  vue-tsc: ^2.1.10
