packages:
  - playground
  - playground-nuxt
  - packages/**
catalog:
  '@antfu/eslint-config': ^3.7.3
  '@babel/types': ^7.25.6
  '@types/fs-extra': ^11.0.4
  '@types/node': ^22.7.4
  '@types/postcss-js': ^4.0.4
  '@unocss/core': ^0.63.1
  '@unocss/eslint-plugin': ^0.63.1
  '@unocss/nuxt': ^0.63.1
  '@unocss/preset-attributify': ^0.63.1
  '@unocss/preset-icons': ^0.63.1
  '@unocss/preset-mini': ^0.63.1
  '@unocss/preset-rem-to-px': ^0.63.1
  '@unocss/preset-tagify': ^0.63.1
  '@unocss/preset-typography': ^0.63.1
  '@unocss/preset-uno': ^0.63.1
  '@unocss/preset-web-fonts': ^0.63.1
  '@unocss/transformer-compile-class': ^0.63.1
  '@unocss/transformer-directives': ^0.63.1
  '@unocss/transformer-variant-group': ^0.63.1
  '@vitejs/plugin-vue': ^5.1.4
  bumpp: ^9.6.1
  eslint: ^9.11.1
  esno: ^4.8.0
  fs-extra: ^11.2.0
  lint-staged: ^15.2.10
  magic.css: ^1.4.8
  nuxt: ^3.13.2
  postcss: ^8.4.47
  postcss-js: ^4.0.1
  simple-git-hooks: ^2.11.1
  taze: ^0.17.2
  typescript: ^5.6.2
  unbuild: ^2.0.0
  unocss: ^0.63.1
  unocss-preset-scrollbar: ^0.3.1
  vite: ^5.4.8
  vitest: ^2.1.1
  vue: ^3.5.10
  vue-tsc: ^2.1.6
