packages:
  - playground
  - playground-nuxt
  - packages/**
catalog:
  '@antfu/eslint-config': ^2.26.1
  '@babel/types': ^7.25.2
  '@types/fs-extra': ^11.0.4
  '@types/node': ^22.4.2
  '@types/postcss-js': ^4.0.4
  '@unocss/core': ^0.62.2
  '@unocss/eslint-plugin': ^0.62.2
  '@unocss/nuxt': ^0.62.2
  '@unocss/preset-attributify': ^0.62.2
  '@unocss/preset-icons': ^0.62.2
  '@unocss/preset-mini': ^0.62.2
  '@unocss/preset-rem-to-px': ^0.62.2
  '@unocss/preset-tagify': ^0.62.2
  '@unocss/preset-typography': ^0.62.2
  '@unocss/preset-uno': ^0.62.2
  '@unocss/preset-web-fonts': ^0.62.2
  '@unocss/transformer-compile-class': ^0.62.2
  '@unocss/transformer-directives': ^0.62.2
  '@unocss/transformer-variant-group': ^0.62.2
  '@vitejs/plugin-vue': ^5.1.2
  unocss: ^0.62.2
  bumpp: ^9.5.1
  eslint: ^9.9.0
  esno: ^4.7.0
  fs-extra: ^11.2.0
  lint-staged: ^15.2.9
  magic.css: ^1.4.8
  nuxt: ^3.13.0
  postcss: ^8.4.41
  postcss-js: ^4.0.1
  simple-git-hooks: ^2.11.1
  unbuild: ^2.0.0
  typescript: ^5.5.4
  unocss-preset-scrollbar: ^0.3.1
  vite: ^5.4.2
  vitest: ^2.0.5
  vue: ^3.4.38
  vue-tsc: ^2.0.29
