name: CI

on:
  push:
    branches:
      - wind3

  pull_request:
    branches:
      - wind3

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set node LTS ✨
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm 🚀
        uses: pnpm/action-setup@v4

      - name: Install
        run: pnpm i

      - name: PNPM build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
