name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set node LTS ✨
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm 🚀
        uses: pnpm/action-setup@v4

      - name: Install
        run: pnpm install

      - name: PNPM build
        run: pnpm build

      - name: Test
        run: pnpm test

      - run: pnpm dlx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

      - name: Config npm
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: pnpm -r publish --access public --no-git-checks
